theme: 'readable'
title: 'RogueFoam'

languages:
  en:
    #taxonomies:
      #hobby: hobbies
    languageName: English
    menu:
      main:
      - name: Blog
        url: /posts
        weight: 10
      - name: Home
        url: /
        weight: 1